### ISSUE TITLE
vue3之中不能正常使用么？

### ISSUE THREAD

**Issue by lee-stars** [BiYuqi/vue-intersection-observer#35]
浏览器控制台报错如下：
`vue-intersection-observer.umd.min.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.c (vue-intersection-observer.umd.min.js:1:20630)
    at renderComponentRoot (runtime-core.esm-bundler.js:890:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5602:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5716:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5730:9)
    at mountComponent (runtime-core.esm-bundler.js:5512:9)
    at processComponent (runtime-core.esm-bundler.js:5470:17)
    at patch (runtime-core.esm-bundler.js:5060:21)
    at mountChildren (runtime-core.esm-bundler.js:5256:13)
c @ vue-intersection-observer.umd.min.js:1
renderComponentRoot @ runtime-core.esm-bundler.js:890
componentUpdateFn @ runtime-core.esm-bundler.js:5602
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5716
setupRenderEffect @ runtime-core.esm-bundler.js:5730
mountComponent @ runtime-core.esm-bundler.js:5512
processComponent @ runtime-core.esm-bundler.js:5470
patch @ runtime-core.esm-bundler.js:5060
mountChildren @ runtime-core.esm-bundler.js:5256
processFragment @ runtime-core.esm-bundler.js:5429
patch @ runtime-core.esm-bundler.js:5053
mountChildren @ runtime-core.esm-bundler.js:5256
mountElement @ runtime-core.esm-bundler.js:5165
processElement @ runtime-core.esm-bundler.js:5137
patch @ runtime-core.esm-bundler.js:5057
componentUpdateFn @ runtime-core.esm-bundler.js:5609
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5716
setupRenderEffect @ runtime-core.esm-bundler.js:5730
mountComponent @ runtime-core.esm-bundler.js:5512
processComponent @ runtime-core.esm-bundler.js:5470
patch @ runtime-core.esm-bundler.js:5060
mountChildren @ runtime-core.esm-bundler.js:5256
mountElement @ runtime-core.esm-bundler.js:5165
processElement @ runtime-core.esm-bundler.js:5137
patch @ runtime-core.esm-bundler.js:5057
mountChildren @ runtime-core.esm-bundler.js:5256
mountElement @ runtime-core.esm-bundler.js:5165
processElement @ runtime-core.esm-bundler.js:5137
patch @ runtime-core.esm-bundler.js:5057
componentUpdateFn @ runtime-core.esm-bundler.js:5609
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5716
setupRenderEffect @ runtime-core.esm-bundler.js:5730
mountComponent @ runtime-core.esm-bundler.js:5512
processComponent @ runtime-core.esm-bundler.js:5470
patch @ runtime-core.esm-bundler.js:5060
componentUpdateFn @ runtime-core.esm-bundler.js:5609
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5716
setupRenderEffect @ runtime-core.esm-bundler.js:5730
mountComponent @ runtime-core.esm-bundler.js:5512
processComponent @ runtime-core.esm-bundler.js:5470
patch @ runtime-core.esm-bundler.js:5060
render2 @ runtime-core.esm-bundler.js:6231
mount @ runtime-core.esm-bundler.js:4424
app.mount @ runtime-dom.esm-bundler.js:1606
(匿名) @ main.js?t=1664128985525:19
Show 19 more frames`

**Comment by crytoplus** [comment]
@lee-stars 你好，还不支持vue3

**Comment by wobsoriano** [comment]
Just use https://vueuse.org/core/useIntersectionObserver/
